# ~/.bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Don't put duplicate lines or lines starting with spaces in the history
HISTCONTROL=ignoreboth

# Set history length
HISTSIZE=1000
HISTFILESIZE=2000

# Append to the history file
shopt -s histappend

# Check window size after each command
shopt -s checkwinsize

# Enable the ** glob pattern
shopt -s globstar

# Make less more friendly for non-text files
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# Enable color support for ls and grep
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Colored gcc warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# Enable programmable completion features
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# mkn completion
complete -W "$(ls --color=never $MKN_TEMPLATES)" mkn

# Source ~/.bash_aliases if it exists
[ -f ~/.bash_aliases ] && . ~/.bash_aliases

# Source ~/.test_aliases if it exists
[ -f ~/.test_aliases ] && . ~/.test_aliases
